Generalized propulsion functions
MIT-LAE/TASOPT.jl pull request #113
Opened 2024-12-16 13:51 UTC by ngomezve

This PR introduces new engine functions: `enginecalc!` and `engineweight!` that replace the engine function calls. These functions act as handles for any propulsion function that can use the same syntax, e.g., do design or off-design cases.

The `enginecalc!` and `engineweight!`  functions are stored and then extracted from a new `Engine` object produced when the input file is read. The user is free to then replace those functions with others if a more custom propulsion option is desired.

The old turbofan functions are now stored in a dedicated `turbofan` folder inside `src/engine`. New functions called `tfwrap!` and `tfweightwrap!` have been created as wrappers for the old functions and related pieces of code, such that these can be called by the generalized functions.

2025-01-27 15:07 UTC, ngomezve commented on src/misc/engine.jl
> +    weight_model::Function = (x->x)
Thanks for the comments! Will get started on the updates.

2025-01-29 16:42 UTC, ngomezve commented
I made the changes suggested by @askprash. The code is still somewhat slower and with more allocations than `main`; not totally sure why. In `main`, the default aircraft median sizing time is 62.773 ms with 663255 allocations. In `dev_generalprop`, the median time is 64.327 ms with 706241 allocations.

2025-02-05 16:34 UTC, argonaut22 commented on src/sizing/wsize.jl
good streamlining. only note, `case` might be a good variable to start with the string option style (i.e., `opt_case`)

2025-02-05 16:38 UTC, argonaut22 commented on src/engine/engine.jl
> +export tfweightwrap!, tfweight, ddct, ddat, gct, gat, tfsize!, Ncmap, ecmap, Ncmap1, ecmap1, etmap, Pimap, tfoper!
do we actually need all of these vars exported to the main namespace? I see that they were there before, but may as well prune if they're not needed

2025-02-05 22:10 UTC, argonaut22 commented on src/misc/engine.jl
> +    heat_exchangers::Vector{HX_struct}
can we do this without the heat exchangers in every model? i think the superclass should be as general as possible, and it's not clear to me/users why `HX_struct`s have a special position.

2025-02-05 22:14 UTC, argonaut22 commented on src/engine/turbofan/tfwrap.jl
> +    - `initeng::Int64`: flag to initialize engine
getting ahead of the flag style PR, can we rename `initeng::Int64` to `initializes_engine::Bool`

2025-02-05 22:17 UTC, argonaut22 commented on src/engine/turbofan/tfwrap.jl
> +    pari = ac.pari
`pari, parg, _, para, pare, _, _, wing, _, _, _= unpack_ac(ac)` ?

2025-02-05 22:18 UTC, argonaut22 commented on src/engine/turbofan/tfwrap.jl
> +        ichoke5, ichoke7 = tfcalc!(pari,parg,view(para, :, ip), view(pare, :, ip), wing, ip, icall, icool, inite1)
again, flag style preemption: `inite1` -> `initializes_engine_firstiter` ?

2025-02-05 22:25 UTC, argonaut22 commented on src/engine/turbofan/tfwrap.jl
> +        icool = 1
again again, flag style preemption:. this one is a bit more openended since we haven't yet propagated string-based `opt`s
- `icall::Int64` -> `opt_call::String` can be `"sizing", "oper_Tt4", "oper_Fe"`
- `icool` -> `opt_cooling::String` can be `"none", "fixed_flowratio", "fixed_Tmetal"`

2025-02-05 22:42 UTC, argonaut22 requested changes
Great work overall. Generalization has been an open question for a bit, and big fan of unpack_ac. 

Left a few notes centering around:
1. flag style propagation (secondary, but we should get rolling on this)
2. including HX in the most general functions seems unintuitive
3. misc tweaks

2025-02-07 16:20 UTC, ngomezve commented on src/engine/engine.jl
> +export tfweightwrap!, tfweight, ddct, ddat, gct, gat, tfsize!, Ncmap, ecmap, Ncmap1, ecmap1, etmap, Pimap, tfoper!
Good catch; some of those functions no longer exist

2025-02-07 16:22 UTC, ngomezve commented on src/IO/read_input.jl
That's a good addition and something that we should definitely do in the future. For this PR, I wanted to focus on the changes to the code while minimizing changes to the inputs, but definitely something to consider.

2025-02-07 16:50 UTC, ngomezve commented on src/misc/engine.jl
> +    heat_exchangers::Vector{HX_struct}
The thought is that there will be more engine elements and the HX one is the only one implemented right now. In the future we could have turbomachinery as well.

2025-02-07 16:50 UTC, ngomezve commented on src/misc/engine.jl
> +    heat_exchangers::Vector{HX_struct}
I added a todo comment to clarify it

2025-02-07 16:52 UTC, ngomezve commented on src/engine/turbofan/tfweightwrap.jl
> +function tfweightwrap!(ac, HXs)
Agreed and done

2025-02-07 18:19 UTC, argonaut22 commented on src/engine/turbofan/tfwrap.jl
> +    pari = ac.pari
oh interesting. i had not considered build order to this point, but makes sense

I got it to work by sticking the fxns in `misc/unpack_ac.jl` and building before `include(__TASOPTindices__)`. thoughts on this strategy? @askprash ? 

i can commit and push if we like it

2025-02-07 18:24 UTC, ngomezve commented on src/engine/turbofan/tfwrap.jl
> +    - `initeng::Int64`: flag to initialize engine
Done

2025-02-07 18:27 UTC, ngomezve commented on src/engine/turbofan/tfwrap.jl
> +        ichoke5, ichoke7 = tfcalc!(pari,parg,view(para, :, ip), view(pare, :, ip), wing, ip, icall, icool, inite1)
I made the change although I'm not convinced that the syntax is much better

2025-02-07 18:29 UTC, ngomezve commented on src/engine/turbofan/tfwrap.jl
> +        icool = 1
This is potentially a good improvement but it would require changes to `tfcalc!`. My goal with this PR is lay out a data structure that could work with any function so I'd rather avoid this for simplicity now.

2025-02-07 18:33 UTC, argonaut22 commented on src/engine/turbofan/tfwrap.jl
> +        icool = 1
if it's not in this PR, it'll be in #98 next so the changes have to happen anyway. 

Given your familiarity, do you foresee any issues or is it only going through ctrl-f?

2025-02-10 16:33 UTC, ngomezve commented on src/engine/turbofan/tfwrap.jl
> +    pari = ac.pari
Fixed the issue by splitting `misc/aircraft.jl` into two files so that the helper functions can be loaded separately.

2025-02-10 16:35 UTC, ngomezve commented on src/engine/turbofan/tfwrap.jl
> +        icool = 1
Probably no major issues. We'll probably have to adapt the syntax in `wsize()` to accommodate the change in flags, but I don't anticipate this breaking anything.

2025-02-10 20:44 UTC, argonaut22 approved these changes

2025-02-10 20:53 UTC, argonaut22 approved these changes

2025-02-10 20:58 UTC, argonaut22 approved these changes

2025-02-10 21:15 UTC, merged