Plots.jl Refactor (goodbye PythonPlot)
MIT-LAE/TASOPT.jl pull request #114
Opened 2024-12-16 21:21 UTC by argonaut22

This PR:
- surgically excises the metastasized plt usage (so we're not installing a GB of python just to plot)
- replaces it in all places with plt-like plotter, Plots.jl (see `outputs.jl` for extensive sample usage)
- Splits `outputs.jl` into `text_outputs.jl` and `plot_outputs.jl`
- ensures all of this is tested such that changes to data structure will show a break

Note:
- some TODO's are marked where the originally-intended functionality appears absent. Of note: `label_bars()` which is now replaced with simple legends in the plot
- data IO tests are re-instated, broken tests are appropriately marked. some are /still/ commented out since they're dependent on the data struct handling task, but they're marked as TODO
- there may be a better plotting backend to select that would allow direct copying from VScode/etc. Unclear what that is rn

Sample outputs:
![image](https://github.com/user-attachments/assets/ec0711b0-7023-43fe-9e84-1096a02c59fb)
![image](https://github.com/user-attachments/assets/dd0fef62-68bd-4b79-a4fa-0d1f1cc9a626)

2024-12-17 09:49 UTC, aditeyashukla commented on example/example_PRD.jl
guessing this will have to change with Nico's PR about the payload range/woper updates

2024-12-17 09:52 UTC, aditeyashukla reviewed
Looks great! 
Will need updates once Wing/tail PR and Woper PR are merged
Happy to help for updates regarding the former

2024-12-18 21:24 UTC, argonaut22 commented on src/IO/outputs.jl
> +    find_aerodrome_code(bmax) = (["C", "III"], bmax)  # Replace with actual function
good eye. the function is still here (in this version, line 624) but looks like a placeholder overstayed its welcome. will fix

2025-01-15 11:04 UTC, argonaut22 commented
Rebased onto b6129e2 (from #73)
propagating wing changes through to `save_model.jl` and other overlooked files

2025-01-16 12:53 UTC, argonaut22 commented
Replaced some straggler references to wing parg[] vars. 

Marked newly-broken IO tests which will be fixed as another PR. Aiming to do this before additional struct introductions so that the variable changes can be done at once and systematically.

Review and pull before other stuff changes plssss

2025-01-16 12:57 UTC, argonaut22 commented
Also of note:
- found some inconsistencies between the code and the var name spreadsheet. made changes to the spreadsheet. be on the lookout
- #74 is still pending, though the triaging for it is done here

2025-01-16 15:51 UTC, ngomezve requested changes
Good PR. PythonPlots is very difficult to install properly. There are a few issues with functionality that we used to have that seems to be broken; for example, LH2 tanks not showing or only some seats being displayed.

2025-01-16 15:51 UTC, ngomezve commented on src/IO/output_plots.jl
In the future, consider using `git mv` to rename files when you are keeping most of the content. This way, the diffs are properly tracked.

2025-01-16 15:51 UTC, ngomezve commented on src/IO/output_plots.jl
> +    if pari[iidoubledeck] == 0
Not all seats are currently being shown. Is this by design? It would be good to see if aircraft are single or twin aisle

2025-01-16 15:51 UTC, ngomezve commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[:, m], yt[:, m], fillrange=-yt[:, m], color=:red, alpha=0.1, z_order=6, linewidth=1.0)
The tank is currently not being shown. Please run `example/example_cryo.jl` to see an example hydrogen aircraft and how it looks.

2025-01-16 15:51 UTC, ngomezve commented on src/IO/output_plots.jl
> +function PayloadRange(ac_og; Rpts = 20, Ppts = 20, filename = "PayloadRangeDiagram.png", OEW = false)
This function will be extensively modified in PR #109. There will be conflicts...

2025-01-16 15:51 UTC, ngomezve commented on src/IO/output_texts.jl
Good split! Outputs was unnecessarily long.

2025-01-17 08:00 UTC, argonaut22 commented on src/IO/output_plots.jl
> +function PayloadRange(ac_og; Rpts = 20, Ppts = 20, filename = "PayloadRangeDiagram.png", OEW = false)
The primary value-add here is the plotting. everything else is broadly as it was. 

Thus, i don't think it'll be too bad to merge so long as the plotted variables remain the same.

2025-01-17 08:01 UTC, argonaut22 commented on src/IO/output_plots.jl
> +    if pari[iidoubledeck] == 0
looking into it

2025-01-17 08:22 UTC, argonaut22 commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[:, m], yt[:, m], fillrange=-yt[:, m], color=:red, alpha=0.1, z_order=6, linewidth=1.0)
would you mind dropping a screenshot here? Troubleshooting `PythonPlot` is anathema to me after all this

2025-01-17 12:28 UTC, argonaut22 commented on src/IO/output_plots.jl
> +    if pari[iidoubledeck] == 0
et voila

![image](https://github.com/user-attachments/assets/28e8f07c-cd5a-45dc-9650-53da6d5cb4cc)

2025-01-17 13:42 UTC, askprash commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[:, m], yt[:, m], fillrange=-yt[:, m], color=:red, alpha=0.1, z_order=6, linewidth=1.0)
Double check the z_orders

2025-01-23 01:27 UTC, argonaut22 commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[:, m], yt[:, m], fillrange=-yt[:, m], color=:red, alpha=0.1, z_order=6, linewidth=1.0)
indexing error turns out. `xt[m, :]`, not `[:,m]`

2025-01-23 01:28 UTC, argonaut22 commented on example/example_PRD.jl
just a matter of switching the function name, huzzah

2025-01-29 15:30 UTC, ngomezve commented on src/IO/output_plots.jl
> +        plot!(plot_obj, [0.0, xf[end]], [yloc, yloc], lw=1.5, arrow=:h, color=:black, label="")
```suggestion
        plot!(plot_obj, [0.0, xf[end]], [yloc, yloc], lw=1.5, arrow=:both, color=:black, label="")
```

2025-01-29 15:44 UTC, ngomezve commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[m,:], yt[m,:], fillrange=-yt[m,:], color=:red, alpha=0.1, z_order=4, linewidth=1.0)
```suggestion
            plot!(xt[m, :], yt[m, :], fill_between=(-yt[m, :], yt[m, :]), color=:red, alpha=0.1)
```

2025-01-29 15:45 UTC, ngomezve commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[m,:], yt[m,:], fillrange=-yt[m,:], color=:red, alpha=0.1, z_order=4, linewidth=1.0)
The original code does not work but the suggestion should.

2025-01-29 15:50 UTC, ngomezve reviewed
Good job improving the PR. I think it is almost there. I made a couple of small suggestions on how to improve the stickfig so that the length arrow and the tank color fill show properly. 

On the payload-range diagram, this PR removes some functionality I added on the previous one, namely the PFEI plot is no longer shown. It would be nice if this were added again.

2025-01-29 15:50 UTC, ngomezve commented on src/IO/outputs.jl
> -    PFEIsToPlot = []
Why did you remove the PFEI plot? I think it is a nice addition to the payload-range plot...

2025-01-29 15:57 UTC, ngomezve commented on src/IO/outputs.jl
> -    PFEIsToPlot = []
Is the behavior on the drag and mass details expected? I believe the subplots need to be adjusted.

![Example](https://github.com/user-attachments/assets/08b8b495-5639-451e-974e-26bd884f41ca)

2025-01-30 05:46 UTC, argonaut22 commented on src/IO/output_plots.jl
> +            plot!(plot_obj, xt[m,:], yt[m,:], fillrange=-yt[m,:], color=:red, alpha=0.1, z_order=4, linewidth=1.0)
good catch. dunno what happened there

2025-01-30 06:26 UTC, argonaut22 commented
Thanks Nico. Fixed:
![image](https://github.com/user-attachments/assets/3bc1d597-dd89-481c-a4a6-40677a1c0523)
![image](https://github.com/user-attachments/assets/22be1c7d-b19e-4e3d-a435-b3aaca163eed)

The empty weight breakdown raises an eyebrow

2025-01-30 21:40 UTC, ngomezve reviewed
Very good improvements once again. Only issue is that the test file is too verbose because of unnecessary outputs. Probably fixable in one commit.

2025-01-30 21:40 UTC, ngomezve commented on test/unit_test_io.jl
> +    size_aircraft!(ac_quick, Ldebug=true, printiter=true, saveOD=false)
```suggestion
    size_aircraft!(ac_quick, Ldebug=false, printiter=false, saveOD=false)
```

2025-01-30 21:40 UTC, ngomezve commented on src/IO/output_plots.jl
> +function PayloadRange(ac_og::TASOPT.aircraft;
Add verbosity switch to prevent long outputs in tests

2025-01-30 21:40 UTC, ngomezve commented on src/IO/quicksave_load.jl
Nice addition!

2025-01-30 22:26 UTC, ngomezve approved these changes
Approving PR after last changes

2025-01-31 18:03 UTC, ngomezve approved these changes
Approving PR. Thanks @argonaut22 for the improvements.

2025-01-31 18:10 UTC, merged